[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    [en.params]
        introTitle = "Hashmi Mohammed!"
        introCaption = "A clean and simple blog"
        introLink = "/about"
        introLinkTitle = "About"
        license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Follow me"
        socialCaption = "I work on everything coding"