## Homepage
title = "Hashmi"
titleSeparator = "-"
titleAddition = "Clean and simple Blog"
description = "Hashmi is a clean blog"

## Open Graph
images = ["logo.png"]
ogLocale = "en_US"
domainTLD = "hinode-demo.markdumay.org"

## Twitter Cards
# twitterSite = "@gethinode"
# twitterCreator = "@markdumay"

## JSON-LD
schemaType = "Organization"
schemaName = "Hashmi"
schemaAuthor = "Hashmi Mohammed"
schemaAuthorTwitter = "https://twitter.com/hashmi_smf"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/hashmi-mohammed-b343b810a/"
schemaAuthorGitHub = "https://github.com/hashmee"
schemaAuthorGitLab = "https://github.com/hashmi.smf"
schemaLocale = "en-US"
schemaLogo = "img/logo512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "img/logo512x512.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaSection = "blog"


[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[search]
    enabled = true

[toc]
    enabled = true

[style]
    themeColor = "#D43900" #00b0f0
    themeOpacity = "10"

[main]
    featurePhoto = "/img/sunrise.jpg" # source: https://unsplash.com/photos/ZX6BPboJrYk
    logo = "/blog/img/logo_embedded.svg"


[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 
