[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Articles"
  url = "/articles/"
  weight = 20

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 30

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
  url = "https://linkedin.com/"
  weight = 10